### PR TITLE
Removing vcgencmd dependency

### PR DESCRIPTION
**Pull request by PhoGGy**
The temperature as well as the cpu frequency can be easily read from file instead of parsing the output of vcgencmd.

### CODE REVIEW

**Comment by nschloe** [comment]
You need to `make format`.

**Comment by PhoGGy** [comment]
How do I do that? As this is a python script and not a Makefile project, why do I need make?

**Comment by nschloe** [comment]
Well you can make it lint clean any way you like, but running make format is the easiest way. Just open the makefile tomsee whatnot does.

**Comment by nschloe** [comment]
Looking at the code, I noticed that we already have something for this. Just provide `filename` to `measure_temp` and you get what you want.

**Pull request closed without merging**
