### PR TITLE
convert to matplotx from dufte, fixes #118

### LINKED ISSUE #118: Can you update for deprecation of python-dufte
I see [dufte](https://github.com/nschloe/dufte#deprecation) is deprecated and replaced.  Can you update stressberry to work with the replacement?  When I try:
```
% stressberry-run -n "comments" fan.dat                                                           
Awaiting stable baseline temperature...
...
% stressberry-plot -o caseless.png -f -l 200 2200 -t 20 90 fan.dat 
Traceback (most recent call last):
  File "/usr/bin/stressberry-plot", line 8, in <module>
    sys.exit(plot())
  File "/usr/lib/python3.9/site-packages/stressberry/cli/plot.py", line 9, in plot
    import dufte
ModuleNotFoundError: No module named 'dufte'
```

Upstream or am I doing something wrong?

### PR DESCRIPTION
**Pull request by graysky2**
I am not python-savvy by any means but I think this does the job.  Build environment for me was having `python-matplotx` substituting in for `python-dufte` (all other depds/makedeps on board).

* graphs a file correctly ie `stressberry-plot -o caseless2.png -f -l 200 2200 -t 20 90 fan.dat` gives the expected plot.
* passes tests
```
% mkdir -p temp
% site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
% python -m install --optimize=1 --destdir=temp dist/*.whl
%PATH="$PWD/temp/usr/bin:$PATH" PYTHONPATH="$PWD/temp/$site_packages" python -m pytest
['/usr/lib/python3.9/site-packages/install/_vendor/installer/src', '/scratch/stressberry/src/stressberry-0.3.3', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/lib/python3.9/site-packages']
Listing '.install-cache/pkg'...
Listing '.install-cache/pkg/stressberry'...
Compiling '.install-cache/pkg/stressberry/__about__.py'...
Compiling '.install-cache/pkg/stressberry/__init__.py'...
Listing '.install-cache/pkg/stressberry/cli'...
Compiling '.install-cache/pkg/stressberry/cli/__init__.py'...
Compiling '.install-cache/pkg/stressberry/cli/helpers.py'...
Compiling '.install-cache/pkg/stressberry/cli/plot.py'...
Compiling '.install-cache/pkg/stressberry/cli/run.py'...
Compiling '.install-cache/pkg/stressberry/main.py'...
Listing '.install-cache/pkg/stressberry-0.3.3.dist-info'...
===================================================== test session starts ======================================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /scratch/stressberry/src/stressberry-0.3.3
collected 2 items                                                                                                              

test/test_cli.py .                                                                                                       [ 50%]
test/test_stressberry.py .                                                                                               [100%]

====================================================== 2 passed in 27.55s ======================================================
```

### CODE REVIEW

**Comment by nschloe** [comment]
- matplotx should be added to `setup.cfg`
- instead of `plt.legend()` use, `matplotx.line_labels()`.

**Comment by graysky2** [comment]
>matplotx should be added to setup.cfg

I replaced `dufte` with `matplotx` although I see now your wording was 'added' not 'replaced' let me know if I need to fix that.

**Comment by nschloe** [comment]
`dufte` needs to be removed from `setup.py`, too. Can you also bump the Python requirements to 3.7 in the same file and in `.github/workflow/ci.yml`?

**Comment by graysky2** [comment]
Sure, see latest

**Comment by nschloe** [comment]
remove `Programming Language :: Python :: 3.6`

**Comment by shortbloke** [comment]
This PR doesn't completely replace the changes I proposed in #111 as that also added back capabilities to:
- Hide the legend
- Adjust the line width
- Use a style that was more appropriate for those with color vision impairments.

Is the "fixes nschloe#111" incorrect and should be relating to a different issue?

**Comment by graysky2** [comment]
> Is the "fixes #111" incorrect and should be relating to a different issue?

That is in reference to https://github.com/nschloe/stressberry/issues/118 ... typo now corrected

**Comment by nschloe** [comment]
Thanks!

**Pull request merged**
